name: Deploy

on:
  push:
    branches:
    - master
    - github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: set Auth Server URL
      run: echo "NEXT_PUBLIC_SKYWAY_AUTH_SERVER_URL=${{ secrets.NEXT_PUBLIC_SKYWAY_AUTH_SERVER_URL }}" > .env
    - name: npm run build
      run: npm run build
    - name: deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=.next
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
